import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-[100px] flex-col justify-center  w-full">
          <div className="  flex  flex-col justify-center items-center  ">
            <Header />
            <br />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
