import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Image } from "@/components/Image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex gap-[100px] flex-col items-center">
        <div className="flex justify-center text-center items-center ">
          <div className="flex w-[1920px] items-center flex-col  gap-24">
            <Header />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
